HOSTNAME="127.0.0.1"
PORT=3306
USERNAME="root"
PASSWORD="root"
DATABASE="myapp"
SECRET_KEY='Jude the Obscure'
SQLALCHEMY_DATABASE_URI=f'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4'